POST http://localhost:8080/api/message/FirstTopic
Content-Type: application/json

{
  "author":"aaaa",
  "content":"aaaaa"
}

###

POST http://localhost:8080/api/message/NewTopic
Content-Type: application/json

{
"author":"xxx",
"content":"x x xx x x"
}
