GET http://localhost:8080/api/info
Accept: application/json

###
POST http://localhost:8080/api/info
Authorization: Basic user user
Content-Type: application/json
Accept: application/json

{
        "tile": "y",
        "content": "yyy"
}

###
DELETE http://localhost:8080/api/info
Authorization: Basic admin admin
Content-Type: application/json
Accept: application/json

{
  "tile": "y",
  "content": "yyy"
}

###
